<?php
/**
 * Title: wp-custom-template-faq
 * Slug: journey-turism/wp-custom-template-faq
 * Categories: hidden
 * Inserter: no
 */
?>
<!-- wp:template-part {"slug":"header","area":"header"} /-->

<!-- wp:cover {"url":"<?php echo esc_url( get_stylesheet_directory_uri() ); ?>/assets/images/japan2.jpg","hasParallax":true,"dimRatio":80,"overlayColor":"custom-color-3","isUserOverlayColor":true,"minHeight":15,"minHeightUnit":"rem","isDark":false,"align":"full","style":{"spacing":{"margin":{"top":"0","bottom":"0"}}},"layout":{"type":"default"}} -->
<div class="wp-block-cover alignfull is-light has-parallax" style="margin-top:0;margin-bottom:0;min-height:15rem"><span aria-hidden="true" class="wp-block-cover__background has-custom-color-3-background-color has-background-dim-80 has-background-dim"></span><div class="wp-block-cover__image-background  has-parallax" style="background-position:50% 50%;background-image:url('<?php echo esc_url( get_stylesheet_directory_uri() ); ?>/assets/images/japan2.jpg')"></div><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","style":{"typography":{"fontStyle":"normal","fontWeight":"700"}},"fontSize":"x-large","fontFamily":"tenor-sans"} -->
<p class="has-text-align-center has-tenor-sans-font-family has-x-large-font-size" style="font-style:normal;font-weight:700">FAQ</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover -->

<!-- wp:group {"style":{"background":{"backgroundImage":{"url":"<?php echo esc_url( get_stylesheet_directory_uri() ); ?>/assets/images/line-black-1-1.png","id":800,"source":"file","title":"line-black-1-1"},"backgroundRepeat":"no-repeat","backgroundSize":"contain"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:group {"align":"wide","style":{"spacing":{"margin":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"},"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|30","right":"var:preset|spacing|30"},"blockGap":"var:preset|spacing|60"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignwide" style="margin-top:var(--wp--preset--spacing--60);margin-bottom:var(--wp--preset--spacing--60);padding-top:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--50);padding-left:var(--wp--preset--spacing--30)"><!-- wp:details {"showContent":true,"align":"wide","style":{"elements":{"link":{"color":{"text":"var:preset|color|custom-color-2"}}},"spacing":{"blockGap":"var:preset|spacing|40","padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|60","right":"var:preset|spacing|60"}},"border":{"width":"2px"}},"borderColor":"custom-color-2","textColor":"custom-color-2","className":"fade-up","fontSize":"medium","fontFamily":"tenor-sans"} -->
<details class="wp-block-details alignwide fade-up has-border-color has-custom-color-2-border-color has-custom-color-2-color has-text-color has-link-color has-tenor-sans-font-family has-medium-font-size" style="border-width:2px;padding-top:var(--wp--preset--spacing--40);padding-right:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--40);padding-left:var(--wp--preset--spacing--60)" open><summary>What is JourneyTourism?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block","style":{"elements":{"link":{"color":{"text":"var:preset|color|custom-color-1"}}},"typography":{"letterSpacing":"0.18px","fontStyle":"normal","fontWeight":"400"}},"textColor":"custom-color-1","fontSize":"smallbig","fontFamily":"roboto"} -->
<p class="has-custom-color-1-color has-text-color has-link-color has-roboto-font-family has-smallbig-font-size" style="font-style:normal;font-weight:400;letter-spacing:0.18px">Risus sed vulputate odio ut. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna.&nbsp;</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->

<!-- wp:details {"align":"wide","style":{"elements":{"link":{"color":{"text":"var:preset|color|custom-color-2"}}},"spacing":{"blockGap":"var:preset|spacing|40","padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|60","right":"var:preset|spacing|60"}},"border":{"width":"2px"}},"borderColor":"custom-color-2","textColor":"custom-color-2","className":"fade-up","fontSize":"medium","fontFamily":"tenor-sans"} -->
<details class="wp-block-details alignwide fade-up has-border-color has-custom-color-2-border-color has-custom-color-2-color has-text-color has-link-color has-tenor-sans-font-family has-medium-font-size" style="border-width:2px;padding-top:var(--wp--preset--spacing--40);padding-right:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--40);padding-left:var(--wp--preset--spacing--60)"><summary>What is the cost of a trip?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block","style":{"elements":{"link":{"color":{"text":"var:preset|color|custom-color-1"}}},"typography":{"letterSpacing":"0.18px","fontStyle":"normal","fontWeight":"400"}},"textColor":"custom-color-1","fontSize":"smallbig","fontFamily":"roboto"} -->
<p class="has-custom-color-1-color has-text-color has-link-color has-roboto-font-family has-smallbig-font-size" style="font-style:normal;font-weight:400;letter-spacing:0.18px">Risus sed vulputate odio ut. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna.&nbsp;</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->

<!-- wp:details {"align":"wide","style":{"elements":{"link":{"color":{"text":"var:preset|color|custom-color-2"}}},"spacing":{"blockGap":"var:preset|spacing|40","padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|60","right":"var:preset|spacing|60"}},"border":{"width":"2px"}},"borderColor":"custom-color-2","textColor":"custom-color-2","className":"fade-up","fontSize":"medium","fontFamily":"tenor-sans"} -->
<details class="wp-block-details alignwide fade-up has-border-color has-custom-color-2-border-color has-custom-color-2-color has-text-color has-link-color has-tenor-sans-font-family has-medium-font-size" style="border-width:2px;padding-top:var(--wp--preset--spacing--40);padding-right:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--40);padding-left:var(--wp--preset--spacing--60)"><summary>How hosting works?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block","style":{"elements":{"link":{"color":{"text":"var:preset|color|custom-color-1"}}},"typography":{"letterSpacing":"0.18px","fontStyle":"normal","fontWeight":"400"}},"textColor":"custom-color-1","fontSize":"smallbig","fontFamily":"roboto"} -->
<p class="has-custom-color-1-color has-text-color has-link-color has-roboto-font-family has-smallbig-font-size" style="font-style:normal;font-weight:400;letter-spacing:0.18px">Risus sed vulputate odio ut. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna.&nbsp;</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->

<!-- wp:details {"align":"wide","style":{"elements":{"link":{"color":{"text":"var:preset|color|custom-color-2"}}},"spacing":{"blockGap":"var:preset|spacing|40","padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|60","right":"var:preset|spacing|60"}},"border":{"width":"2px"}},"borderColor":"custom-color-2","textColor":"custom-color-2","className":"fade-up","fontSize":"medium","fontFamily":"tenor-sans"} -->
<details class="wp-block-details alignwide fade-up has-border-color has-custom-color-2-border-color has-custom-color-2-color has-text-color has-link-color has-tenor-sans-font-family has-medium-font-size" style="border-width:2px;padding-top:var(--wp--preset--spacing--40);padding-right:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--40);padding-left:var(--wp--preset--spacing--60)"><summary>Am I entitled to all services?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block","style":{"elements":{"link":{"color":{"text":"var:preset|color|custom-color-1"}}},"typography":{"letterSpacing":"0.18px","fontStyle":"normal","fontWeight":"400"}},"textColor":"custom-color-1","fontSize":"smallbig","fontFamily":"roboto"} -->
<p class="has-custom-color-1-color has-text-color has-link-color has-roboto-font-family has-smallbig-font-size" style="font-style:normal;font-weight:400;letter-spacing:0.18px">Risus sed vulputate odio ut. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna.&nbsp;</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->

<!-- wp:details {"align":"wide","style":{"elements":{"link":{"color":{"text":"var:preset|color|custom-color-2"}}},"spacing":{"blockGap":"var:preset|spacing|40","padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|60","right":"var:preset|spacing|60"}},"border":{"width":"2px"}},"borderColor":"custom-color-2","textColor":"custom-color-2","className":"fade-up","fontSize":"medium","fontFamily":"tenor-sans"} -->
<details class="wp-block-details alignwide fade-up has-border-color has-custom-color-2-border-color has-custom-color-2-color has-text-color has-link-color has-tenor-sans-font-family has-medium-font-size" style="border-width:2px;padding-top:var(--wp--preset--spacing--40);padding-right:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--40);padding-left:var(--wp--preset--spacing--60)"><summary>Can I choose the services I want?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block","style":{"elements":{"link":{"color":{"text":"var:preset|color|custom-color-1"}}},"typography":{"letterSpacing":"0.18px","fontStyle":"normal","fontWeight":"400"}},"textColor":"custom-color-1","fontSize":"smallbig","fontFamily":"roboto"} -->
<p class="has-custom-color-1-color has-text-color has-link-color has-roboto-font-family has-smallbig-font-size" style="font-style:normal;font-weight:400;letter-spacing:0.18px">Risus sed vulputate odio ut. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna.&nbsp;</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->

<!-- wp:details {"align":"wide","style":{"elements":{"link":{"color":{"text":"var:preset|color|custom-color-2"}}},"spacing":{"blockGap":"var:preset|spacing|40","padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|60","right":"var:preset|spacing|60"}},"border":{"width":"2px"}},"borderColor":"custom-color-2","textColor":"custom-color-2","className":"fade-up","fontSize":"medium","fontFamily":"tenor-sans"} -->
<details class="wp-block-details alignwide fade-up has-border-color has-custom-color-2-border-color has-custom-color-2-color has-text-color has-link-color has-tenor-sans-font-family has-medium-font-size" style="border-width:2px;padding-top:var(--wp--preset--spacing--40);padding-right:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--40);padding-left:var(--wp--preset--spacing--60)"><summary>How do I get in touch?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block","style":{"elements":{"link":{"color":{"text":"var:preset|color|custom-color-1"}}},"typography":{"letterSpacing":"0.18px","fontStyle":"normal","fontWeight":"400"}},"textColor":"custom-color-1","fontSize":"smallbig","fontFamily":"roboto"} -->
<p class="has-custom-color-1-color has-text-color has-link-color has-roboto-font-family has-smallbig-font-size" style="font-style:normal;font-weight:400;letter-spacing:0.18px">Risus sed vulputate odio ut. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna.&nbsp;</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:template-part {"slug":"footer","area":"footer"} /-->